namespace MyProject.Helper.Constants.Globals
{
    public enum ResponseCodeEnum
    {
        // Code API
        SUCCESS = 200,
        ERR_SYSTEM = -500,
        ERR_WRONG_INPUT = -101,
        ERR_WRONG_USERNAME_PASS = -102,
        ERR_INVALID_TOKEN = -401,
        ERR_DDOS = -402,
        ERR_API_NOT_FOUND = -403,
        ERR_WALLET_EXIST = -405,
        ERR_NOT_FOUND = -409,
        ERR_SESSION = -406,
        ERR_TIME_OUT = -408,
        ERR_SYMTEM = -500,
        ERR_LOGIN = -99,
        ERR_REGISTER = -98,
        WRR_OTP = -97,
        ERR_EXISTUSER = -96,
        ERR_AGE_NOT_VALID = -95,
        MAIL_NOT_EXIST = -94,
        WRR_TYPE = -93,
        ERR_ENERGY_NOT_ENOUGH = -92,
        ERR_INPUT_STT_STATUS = -91,
        ERR_INVALID_ITEM = -103,
        ERR_INVALID_FEE = -104,
        ERR_INVALID_QUANTITY = -105,
        ERR_INVALID_OPTION = -130,
        ERR_MONEY_NOT_ENOUGH = -106,
        ERR_MESSAGE_NOT_EXIST = -107,
        ERR_USER_NOT_EXIST = -108,
        ERR_QUANTITY_NOT_ENOUGH = -109,
        ERR_RECIPIENT_NOT_EXIST = -110,
        ERR_CHAT_NOT_EXIST = -111,
        ERR_PRODUCT_NOT_EXIST = -112,
        ERR_DISPLAYNAME_EXIST = -113,
        ERR_TOKEN_NOT_ENOUGH = -114,
        ERR_TYPE_NOT_EXIST = -115,
        ERR_WAREHOUSE_NOT_EXIST = -116,
        ERR_ACHIEVEMENT_NOT_EXIST = -117,
        ERR_EMAIL_ALREADY_RESIGTED = -146,
        ERR_DATA_RETURNED_NULL= -119,
        ERR_SELF_BIDDING = -120,
        ERR_AUCTION_NOT_EXISTS = -121,
        ERR_INVALID_BID = -122,
        ERR_CANCEL_AUCTION = -123,
        ERR_OCCURRED = -125,
        ERR_SERVER = -127,
        ERR_SMARTCONTRACT_REVERT = -400,
        ERR_TRANSACTION_FAKE = -152,
        ERR_INVALID_INPUT = -153,
        ERR_OTP_LIMIT = -156,
        ERR_BLOCK_LOGIN = -157,
        ERR_NOT_ENOUGH_FOLLOWER = -160,
        ERR_NOT_IN_LIVESTREAM = -161,
        // Code Validator (-600< and >-700)
        VLD_REQUIRED = -601,
        VLD_MAX_LENGTH = -602,
        VLD_MIN_LENGTH = -603,
        VLD_RANGE_LENGTH = -604,
        VLD_NOT_NEGATIVE = -605,
        VLD_GREATER_THAN_ZERO = -606,
        VLD_MUST_BE_INTEGER = -607,
        VLD_MUST_BE_VALID_TIME_FORMAT = -608
    }
}
